services:
  web:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG:-latest}
    container_name: l3net_web
    restart: always
    ports:
      - "1486:8000"
    environment:
      DJANGO_SETTINGS_MODULE: l3net_web.settings.production
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG:-False}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1}
      DB_NAME: ${DB_NAME:-l3net_db}
      DB_USER: ${DB_USER:-l3net_admin}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      HF_TOKEN: ${HF_TOKEN}
      HF_HUB_CACHE: /tmp/huggingface
    depends_on:
      - db
    volumes:
      - /home/ubuntu/l3net-web/static:/app/static

  db:
    image: postgres:17
    container_name: l3net_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-l3net_db}
      POSTGRES_USER: ${DB_USER:-l3net_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
