services:
  db:
    image: postgres:17
    container_name: l3net_db_local
    restart: always
    environment:
      POSTGRES_DB: l3net_db
      POSTGRES_USER: l3net_admin
      POSTGRES_PASSWORD: l3net_pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  media_data:
