# Generated by Django 5.2.1 on 2025-06-06 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('image_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.CharField(help_text='Version number of the model', max_length=50)),
                ('model_name', models.CharField(help_text='Name of the model', max_length=100)),
                ('model_type', models.CharField(help_text='Type of the model (e.g., classification, regression)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the model version was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the model version was last updated')),
                ('description', models.TextField(blank=True, help_text='Description of the model version', null=True)),
                ('model_path', models.CharField(help_text='Path to the model file', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PredVertebra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('T8', 'T8'), ('T9', 'T9'), ('T10', 'T10'), ('T11', 'T11'), ('T12', 'T12'), ('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4'), ('L5', 'L5'), ('S1', 'S1'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_vertebrae', to='validation.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('vertebra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertebrea', to='validation.predvertebra')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='validation.exam')),
            ],
        ),
        migrations.AddField(
            model_name='predvertebra',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_vertebrae', to='validation.run'),
        ),
        migrations.CreateModel(
            name='PredSeverity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('severity_name', models.CharField(choices=[('Normal/Mild', 'Normal Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Nothing', 'Nothing'), ('Unkown', 'Unknown')], default='Unkown', max_length=20)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('bounding_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_severities', to='validation.polygon')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_severities', to='validation.modelversion')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_severities', to='validation.run')),
            ],
        ),
    ]
