# Generated by Django 5.2.1 on 2025-06-06 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('severity_name', models.CharField(choices=[('Normal/Mild', 'Normal Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Nothing', 'Nothing'), ('Unkown', 'Unknown')], max_length=20)),
                ('bounding_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='validation.polygon')),
                ('pred_severity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='validation.predseverity')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
