# Generated by Django 5.2.1 on 2025-06-09 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygon',
            name='vertebra_id',
        ),
        migrations.AddField(
            model_name='predvertebra',
            name='polygon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_vertebrae', to='validation.polygon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='validation',
            name='bounding_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to='validation.polygon'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='severity_name',
            field=models.CharField(blank=True, choices=[('Normal/Mild', 'Normal Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Nothing', 'Nothing'), ('Unkown', 'Unknown')], max_length=20, null=True),
        ),
    ]
