# Generated by Django 5.2.1 on 2025-06-10 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_remove_polygon_vertebra_id_predvertebra_polygon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='validation',
            unique_together={('pred_severity_id', 'user_id')},
        ),
        migrations.CreateModel(
            name='RunAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False, help_text='True when all predictions in this run have been validated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when validation was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this assignment', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who made this assignment (usually admin/superuser)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_runs', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='validation.run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_completed'], name='validation__user_id_afa270_idx'), models.Index(fields=['run'], name='validation__run_id_720f00_idx'), models.Index(fields=['assigned_at'], name='validation__assigne_19b9b5_idx')],
                'unique_together': {('run', 'user')},
            },
        ),
    ]
