# Generated by Django 5.2.1 on 2025-06-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0006_predseverity_vertebrae_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='predseverity',
            name='exam_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_severities', to='validation.exam'),
        ),
        migrations.AddField(
            model_name='predvertebra',
            name='exam_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_vertebrae', to='validation.exam'),
        ),
        migrations.AlterField(
            model_name='predseverity',
            name='vertebrae_level',
            field=models.CharField(choices=[('L1/L2', 'L1 L2'), ('L2/L3', 'L2 L3'), ('L3/L4', 'L3 L4'), ('L4/L5', 'L4 L5'), ('L5/S1', 'L5 S1'), ('Unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='predseverity',
            unique_together={('run_id', 'exam_id', 'vertebrae_level')},
        ),
        migrations.AlterUniqueTogether(
            name='predvertebra',
            unique_together={('run_id', 'exam_id', 'name')},
        ),
    ]
