# Generated by Django 5.2.1 on 2025-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0007_predseverity_exam_id_predvertebra_exam_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelversion',
            name='model_path',
            field=models.CharField(blank=True, help_text='Path to the model file', max_length=255, null=True),
        ),
    ]
