# Generated by Django 5.2.1 on 2025-07-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0008_alter_modelversion_model_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='validated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
