# Generated by Django 5.2.1 on 2025-07-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0008_alter_modelversion_model_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', help_text='Current status of this run', max_length=20),
        ),
        migrations.AddField(
            model_name='validation',
            name='validated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
