# Generated by Django 5.2.1 on 2025-07-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0009_run_status_validation_validated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='exam',
            name='version',
            field=models.CharField(default='main', help_text='Dataset version/tag from Hugging Face repository', max_length=100),
        ),
    ]
