# Generated by Django 5.2.1 on 2025-07-07 12:25

from django.db import migrations


def update_null_versions(apps, schema_editor):
    """Update all null or empty version fields to 'main'"""
    Exam = apps.get_model('validation', 'Exam')
    
    # Update null versions
    Exam.objects.filter(version__isnull=True).update(version='main')
    
    # Update empty string versions
    Exam.objects.filter(version='').update(version='main')
    
    # Update whitespace-only versions
    for exam in Exam.objects.all():
        if exam.version and exam.version.strip() == '':
            exam.version = 'main'
            exam.save()


def reverse_update_null_versions(apps, schema_editor):
    """Reverse operation - set versions back to null if they were 'main'"""
    # This is optional since we can't really know which ones were originally null
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0010_alter_exam_options_exam_version'),
    ]

    operations = [
        migrations.RunPython(update_null_versions, reverse_update_null_versions),
    ]
