# Generated by Django 5.2.1 on 2025-09-22 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0011_update_null_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='intra_operator_study_name',
            field=models.CharField(blank=True, help_text='Name to group related runs for intra-operator reliability studies', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='original_run',
            field=models.ForeignKey(blank=True, help_text='Original run this is duplicated from (for intra-operator studies)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_runs', to='validation.run'),
        ),
        migrations.AddField(
            model_name='run',
            name='study_type',
            field=models.CharField(default='original', help_text="Type of study: 'original', 'intra_operator_round_2', etc.", max_length=50),
        ),
    ]
