# Generated by Django 5.2.1 on 2025-09-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0012_add_intra_operator_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='assignments_locked',
            field=models.BooleanField(default=False, help_text='If True, prevents new assignments to maintain expert consistency for reliability studies'),
        ),
    ]
